[mlx][wjh] initialize what-just-happened implementation
Signed-off-by: Stepan Blyschak <stepanb@mellanox.com>

diff --git a/files/build_templates/docker_image_ctl.j2 b/files/build_templates/docker_image_ctl.j2
--- a/files/build_templates/docker_image_ctl.j2
+++ b/files/build_templates/docker_image_ctl.j2
@@ -1,10 +1,21 @@
 #!/bin/bash
+{#- single instance containers are still supported (even though it might not look like it) -#}
+{#- if no instance number is passed to this script, $DEV will simply be unset, resulting in docker -#}
+{#- commands being sent to the base container name. E.g. `docker start database$DEV` simply starts -#}
+{#- the container `database` if no instance number is passed since `$DEV` is not defined -#}
 
-# single instance containers are still supported (even though it might not look like it)
-# if no instance number is passed to this script, $DEV will simply be unset, resulting in docker
-# commands being sent to the base container name. E.g. `docker start database$DEV` simply starts
-# the container `database` if no instance number is passed since `$DEV` is not defined
-
+{%- if docker_container_name == "what-just-happened" %}
+WJH_RUN_DIR="/var/run/wjh/"
+DEBUG_COUNTERS_CAPABILITIES_DUMP_NAME="debug_counters.json"
+DEBUG_COUNTERS_CAPABILITIES_DUMP="${WJH_RUN_DIR}/${DEBUG_COUNTERS_CAPABILITIES_DUMP_NAME}"
+PORT_INIT_DONE_KEY="PORT_TABLE:PortInitDone"
+SLEEP_INTERVAL="1"
+MAX_PORT_INIT_DONE_WAIT="90"
+STATE_DB_SEPERATOR="|"
+CONFIG_DB_SEPERATOR="|"
+DEBUG_COUNTER_CAPABILITIES_TABLE="DEBUG_COUNTER_CAPABILITIES"
+DEBUG_COUNTER_TABLE="DEBUG_COUNTER"
+{%- endif %}
 
 {%- if docker_container_name == "database" %}
 link_namespace() {
@@ -64,6 +75,39 @@ function preStartAction()
     fi
 {%- elif docker_container_name == "snmp" %}
     sonic-db-cli STATE_DB HSET 'DEVICE_METADATA|localhost' chassis_serial_number $(decode-syseeprom -s)
+{%- elif docker_container_name == "what-just-happened" %}
+    if [[ ! -z $(sonic-db-cli CONFIG_DB KEYS "${DEBUG_COUNTER_TABLE}${CONFIG_DB_SEPERATOR}*") ]];
+    then
+        echo "Found debug counter configuration; debug counters and what just happened are mutually exlusive"
+        exit 1
+    fi
+
+    # Wait for indication that orchagent finished initialization
+    RETRY_COUNT="0"
+    while [[ -z $(sonic-db-cli APPL_DB KEYS "${PORT_INIT_DONE_KEY}") ]];
+    do
+        (( RETRY_COUNT++ )) && sleep "${SLEEP_INTERVAL}"
+        if [[ "${RETRY_COUNT}" -ge "${MAX_PORT_INIT_DONE_WAIT}" ]];
+        then
+            echo "Failed to wait for orchagent to start"
+            exit 1
+        fi
+    done
+
+    sonic-db-cli STATE_DB EVAL "
+    local keys = redis.call(\"KEYS\", KEYS[1] .. \"${STATE_DB_SEPERATOR}*\")
+    local res = {}
+    for i,k in pairs(keys) do
+    local sres={}
+    local flat_map = redis.call('HGETALL', k)
+    for j = 1, #flat_map, 2 do
+        sres[flat_map[j]] = flat_map[j + 1]
+    end
+    redis.call('DEL', k)
+    res[k] = sres
+    end
+    return cjson.encode(res)
+    " 1 "${DEBUG_COUNTER_CAPABILITIES_TABLE}" > "${DEBUG_COUNTERS_CAPABILITIES_DUMP}"
 {%- else %}
     : # nothing
 {%- endif %}
@@ -211,6 +255,8 @@ start() {
         -v mlnx_sdk_ready:/tmp \
         -e SX_API_SOCKET_FILE=/var/run/sx_sdk/sx_api.sock \
         -v /dev/shm:/dev/shm:rw \
+{%- elif docker_container_name == "what-just-happened" %}
+        -v mlnx_sdk_ready:/tmp \
 {%- else %}
         --tmpfs /tmp \
 {%- endif %}
@@ -245,16 +291,35 @@ stop() {
 {%- endif %}
 }
 
+stopPost() {
+{%- if docker_container_name == "what-just-happened" %}
+    [ -f "${DEBUG_COUNTERS_CAPABILITIES_DUMP}" ] && {
+        echo "restoring debug counters capability information to DB..."
+        sonic-db-cli STATE_DB EVAL "
+        local capabilities = cjson.decode(ARGV[1])
+        for stage in pairs(capabilities) do
+            local stage_capability = capabilities[stage]
+            for k in pairs(stage_capability) do
+                redis.call('hset', stage, k, stage_capability[k])
+            end
+        end
+        " 0 $(cat "${DEBUG_COUNTERS_CAPABILITIES_DUMP}")
+    }
+{%- else %}
+    : # nothing
+{%- endif %}
+}
+
 OP=$1
 DEV=$2 # namespace/device number to operate on
 NET_NS="asic" #name of the network namespace
 
 case "$1" in
-    start|wait|stop)
+    start|wait|stop|stopPost)
         $1
         ;;
     *)
-        echo "Usage: $0 {start namespace(optional)|wait namespace(optional)|stop namespace(optional)}"
+        echo "Usage: $0 {start namespace(optional)|wait namespace(optional)|stop namespace(optional)|stopPost namespace(optional)}"
         exit 1
         ;;
 esac
